Feature/settings
Ilya-Belyanov/Metronome pull request #20
Opened 2021-09-12 17:59 UTC by Ilya-Belyanov

2021-09-12 19:12 UTC, kupns-aka-kupa requested changes
Починить линковку на MSVC

2021-09-12 19:12 UTC, kupns-aka-kupa commented on core/CMakeLists.txt
> +    ${HEADER_FILES_H})
Избавляемся от `qt5_add_resources`
```suggestion
set(PROJECT_SOURCES
    ${SOURCE_FILES}
    ${RESOURCE_FILES}
    ${HEADER_FILES}
    ${HEADER_FILES_H})
```

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/PlayerSettings/CMakeLists.txt
> +qt5_add_resources(PLUGIN_RESOURCES ${RESOURCE_FILES})
Избавится от `qt5_add_resources`

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/PlayerSettings/playersettingscontroller.hpp
> +        VOLUME = 0, BASESOUND = 1, ACCENTSOUND = 2
`enum class` - [Scoped enumerations](https://en.cppreference.com/w/cpp/language/enum)

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TapperSettings/CMakeLists.txt
> +qt5_add_resources(PLUGIN_RESOURCES ${RESOURCE_FILES})
Не забыть, писал выше

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TapperSettings/tappersettingscontroller.hpp
> +    };
`enum class`

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TapperSettings/tappersettingscontroller.hpp
> +    int strongMaxInertia() const {return _strongMaxInertia;}
Функции , реализация которых сразу в _hpp_  помечаем одним из:
- `Q_DECL_RELAXED_CONSTEXPR`
-  `Q_DECL_CONSTEXPR`
- `Q_ALWAYS_INLINE`

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TempoSettings/CMakeLists.txt
> +qt5_add_resources(PLUGIN_RESOURCES ${RESOURCE_FILES})
Не забыть

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TempoSettings/CMakeLists.txt
> +file(GLOB HEADER_FILES_H ${PROJECT_SOURCE_DIR}/*.h)
Все заголовки в _hpp_ и лишние **GLOB** убрать

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TempoSettings/temposettingscontroller.hpp
> +    };
`enum class`

2021-09-12 19:12 UTC, kupns-aka-kupa commented on plugins/TempoSettings/temposettingscontroller.cpp
> +        return;
Так в одну строчку пишем или переносим

2021-09-16 14:43 UTC, Ilya-Belyanov commented on plugins/TempoSettings/temposettingscontroller.hpp
> +    };
Отклоняю, нам они нужны только чтобы хранить числа.

2021-09-17 08:39 UTC, kupns-aka-kupa requested changes
Сборку на **MSVC** и заливаем

2021-09-30 14:25 UTC, kupns-aka-kupa approved these changes

2021-09-30 14:25 UTC, merged